# https://docs.docker.com/compose/overview/
version: '3'
services:
  api:
    build: .
    volumes:                    
      - .:/usr/app/             # Mount host files into container
      - /usr/app/node_modules   # Copies Keeps host empty node_moudles from overwriting the container node_moudles folder
    ports:
      - "8080:8080"
  
  # http://elk-docker.readthedocs.io/
  elk:
    image: sebp/elk:564
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"